hubsrht/blueprints/mailing_lists.py
import json
from flask import Blueprint, render_template, request, redirect, url_for, abort
from hubsrht.projects import ProjectAccess, get_project
from hubsrht.services import lists
from hubsrht.types import Event, EventType
from hubsrht.types import MailingList, Visibility
from srht.config import get_origin
from srht.database import db
from srht.flask import paginate_query
from srht.oauth import current_user, loginrequired
from srht.search import search_by
from srht.validation import Validation

mailing_lists = Blueprint("mailing_lists", __name__)

@mailing_lists.route("/<owner>/<project_name>/lists")
def lists_GET(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.read)
    mailing_lists = (MailingList.query
            .filter(MailingList.project_id == project.id)
            .order_by(MailingList.updated.desc()))
    if not current_user or current_user.id != owner.id:
        mailing_lists = mailing_lists.filter(
                MailingList.visibility == Visibility.PUBLIC)

    terms = request.args.get("search")
    search_error = None
    try:
        mailing_lists = search_by(mailing_lists, terms,
                [MailingList.name, MailingList.description])
    except ValueError as ex:
        search_error = str(ex)

    mailing_lists, pagination = paginate_query(mailing_lists)
    return render_template("mailing-lists.html", view="mailing lists",
            owner=owner, project=project,
            search=terms, search_error=search_error,
            mailing_lists=mailing_lists,
            **pagination)

@mailing_lists.route("/<owner>/<project_name>/lists/new")
@loginrequired
def new_GET(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    # TODO: Pagination
    mls = lists.get_lists(owner)
    mls = sorted(mls, key=lambda r: r["updated"], reverse=True)
    existing = [l.remote_id for l in (MailingList.query
            .filter(MailingList.project_id == project.id)).all()]
    return render_template("mailing-list-new.html", view="new-resource",
            owner=owner, project=project, lists=mls, existing=existing)

def lists_from_template(owner, project, template):
    project_url = url_for("projects.summary_GET",
        owner=owner.canonical_name, project_name=project.name)
    project_url = get_origin("hub.sr.ht", external=True) + project_url
    templates = {
        "public-inbox": ["public-inbox"],
        "announce-devel": [f"{project.name}-announce", f"{project.name}-devel"],
        "announce-devel-discuss": [
            f"{project.name}-announce",
            f"{project.name}-devel",
            f"{project.name}-discuss", 
        ],
    }
    descs = {
        "public-inbox": f"""
General catch-all for patches, questions, and discussions for any of
{current_user.canonical_name}'s projects which do not have their own mailing
list.

When posting patches to this list, please edit the [PATCH] line to include the
specific project you're contributing to, e.g.

    [PATCH {project.name} v2] Add thing to stuff
""",
        f"{project.name}-announce": f"""
Low-volume mailing list for announcements related to the
[{project.name}]({project_url}) project.
""",
        f"{project.name}-devel": f"""
Mailing list for development discussion and patches related to the
[{project.name}]({project_url}) project. For help sending patches to this
list, please consult [git-send-email.io](https://git-send-email.io).
""",
        f"{project.name}-discuss": f"""
Mailing list for end-user discussion and questions related to the
[{project.name}]({project_url}) project.
""",
    }
    template = templates[template]

    for list_name in template:
        desc = descs[list_name]
        list_name = list_name.lower() # Per lists.sr.ht naming rules
        mailing_list = lists.get_list(owner, list_name)
        if mailing_list is not None:
            in_project = [l.remote_id for l in (MailingList.query
                    .filter(MailingList.project_id == project.id)
                    .filter(MailingList.name == list_name)).all()]
            if in_project:
                continue
        else:
            valid = Validation({
                "name": list_name,
                "description": desc,
            })
            mailing_list = lists.create_list(owner, valid)
            if not mailing_list:
                raise Exception(json.dumps(valid.response))

        ml = MailingList()
        ml.remote_id = mailing_list["id"]
        ml.project_id = project.id
        ml.owner_id = project.owner_id
        ml.name = mailing_list["name"]
        ml.webhook_id = -1
        ml.webhook_version = 0
        ml.description = mailing_list["description"]
        if mailing_list["defaultACL"]["browse"]:
            ml.visibility = Visibility.PUBLIC
        else:
            ml.visibility = Visibility.UNLISTED
        db.session.add(ml)
        db.session.flush()

        try:
            ml.webhook_id, ml.webhook_version = lists.create_list_webhook(
                    owner, mailing_list["id"], ml.id)
        except:
            lists.delete_list(owner, mailing_list["id"])
            raise

        event = Event()
        event.event_type = EventType.mailing_list_added 
        event.mailing_list_id = ml.id
        event.project_id = project.id
        event.user_id = project.owner_id
        db.session.add(event)
        db.session.commit()

    return redirect(project_url)

@mailing_lists.route("/<owner>/<project_name>/lists/new", methods=["POST"])
@loginrequired
def new_POST(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    valid = Validation(request)
    if "from-template" in valid:
        template = valid.require("template")
        valid.expect(template in ["public-inbox",
                "announce-devel", "announce-devel-discuss"],
            "Invalid template selection")
        if not valid.ok:
            mls = lists.get_lists(owner)
            mls = sorted(mls, key=lambda r: r["updated"], reverse=True)
            existing = [l.remote_id for l in (MailingList.query
                    .filter(MailingList.project_id == project.id)).all()]
            return render_template("mailing-list-new.html",
                    view="new-resource", owner=owner, project=project,
                    lists=mls, existing=existing **valid.kwargs)
        return lists_from_template(owner, project, template)
    elif "create" in valid:
        mailing_list = lists.create_list(owner, valid)
        if not valid.ok:
            mls = lists.get_lists(owner)
            mls = sorted(mls, key=lambda r: r["updated"], reverse=True)
            existing = [l.remote_id for l in (MailingList.query
                    .filter(MailingList.project_id == project.id)).all()]
            return render_template("mailing-list-new.html",
                    view="new-resource", owner=owner, project=project,
                    lists=mls, existing=existing, **valid.kwargs)
    else:
        list_name = None
        for field in valid.source:
            if field.startswith("existing-"):
                list_name = field[len("existing-"):]
                break
        if not list_name:
            search = valid.optional("search")
            mls = lists.get_lists(owner)
            # TODO: Search properly
            mls = filter(lambda r: search.lower() in r["name"].lower(), mls)
            mls = sorted(mls, key=lambda r: r["updated"], reverse=True)
            existing = [l.remote_id for l in (MailingList.query
                    .filter(MailingList.project_id == project.id)).all()]
            return render_template("mailing-list-new.html",
                    view="new-resource", owner=owner, project=project,
                    lists=mls, existing=existing, search=search)
        mailing_list = lists.get_list(owner, list_name)

    ml = MailingList()
    ml.remote_id = mailing_list["id"]
    ml.project_id = project.id
    ml.owner_id = project.owner_id
    ml.name = mailing_list["name"]
    ml.description = mailing_list["description"]
    if mailing_list["defaultACL"]["browse"]:
        ml.visibility = Visibility.PUBLIC
    else:
        ml.visibility = Visibility.UNLISTED
    ml.webhook_id = -1
    ml.webhook_version = 0
    db.session.add(ml)
    db.session.flush()

    try:
        ml.webhook_id, ml.webhook_version = lists.create_list_webhook(
                owner, mailing_list["id"], ml.id)
    except:
        lists.delete_list(owner, mailing_list["id"])
        raise

    event = Event()
    event.event_type = EventType.mailing_list_added 
    event.mailing_list_id = ml.id
    event.project_id = project.id
    event.user_id = project.owner_id
    db.session.add(event)
    db.session.commit()

    return redirect(url_for("projects.summary_GET",
        owner=owner.canonical_name, project_name=project.name))

@mailing_lists.route("/<owner>/<project_name>/lists/manage")
@loginrequired
def manage_GET(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    mailing_lists = (MailingList.query
            .filter(MailingList.project_id == project.id)
            .order_by(MailingList.updated.desc()))

    terms = request.args.get("search")
    search_error = None
    try:
        mailing_lists = search_by(mailing_lists, terms,
                [MailingList.name, MailingList.description])
    except ValueError as ex:
        search_error = str(ex)

    mailing_lists, pagination = paginate_query(mailing_lists)
    return render_template("mailing-lists-manage.html",
            view="mailing lists", owner=owner, project=project,
            search=terms, search_error=search_error,
            mailing_lists=mailing_lists,
            **pagination)

@mailing_lists.route("/<owner>/<project_name>/lists/delete/<int:list_id>")
@loginrequired
def delete_GET(owner, project_name, list_id):
    owner, project = get_project(owner, project_name, ProjectAccess.write)

hubsrht/blueprints/trackers.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask import abort
from hubsrht.projects import ProjectAccess, get_project
from hubsrht.services import todo
from hubsrht.types import Event, EventType, Tracker, Visibility
from srht.database import db
from srht.flask import paginate_query
from srht.oauth import current_user, loginrequired
from srht.search import search_by
from srht.validation import Validation

trackers = Blueprint("trackers", __name__)

@trackers.route("/<owner>/<project_name>/trackers")
def trackers_GET(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.read)
    trackers = (Tracker.query
            .filter(Tracker.project_id == project.id)
            .order_by(Tracker.updated.desc()))
    if not current_user or current_user.id != owner.id:
        trackers = trackers.filter(Tracker.visibility == Visibility.PUBLIC)

    terms = request.args.get("search")
    search_error = None
    try:
        trackers = search_by(trackers, terms,
                [Tracker.name, Tracker.description])
    except ValueError as ex:
        search_error = str(ex)

    trackers, pagination = paginate_query(trackers)
    return render_template("trackers.html", view="tickets",
            owner=owner, project=project, trackers=trackers,
            search=terms, search_error=search_error,
            **pagination)

@trackers.route("/<owner>/<project_name>/trackers/new")
@loginrequired
def new_GET(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    # TODO: Pagination
    trackers = todo.get_trackers(owner)
    trackers = sorted(trackers, key=lambda r: r["updated"], reverse=True)
    existing = [t.remote_id for t in (Tracker.query
            .filter(Tracker.project_id == project.id)).all()]
    return render_template("tracker-new.html", view="new-resource",
            owner=owner, project=project, trackers=trackers, existing=existing)

@trackers.route("/<owner>/<project_name>/trackers/new", methods=["POST"])
@loginrequired
def new_POST(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    valid = Validation(request)
    if "create" in valid:
        remote_tracker = todo.create_tracker(owner, valid, project.visibility)
        trackers = todo.get_trackers(owner)
        trackers = sorted(trackers, key=lambda r: r["updated"], reverse=True)
        if not valid.ok:
            existing = [t.remote_id for t in (Tracker.query
                    .filter(Tracker.project_id == project.id)).all()]
            return render_template("tracker-new.html",
                    view="new-resource", owner=owner, project=project,
                    trackers=trackers, existing=existing, **valid.kwargs)
    else:
        tracker_name = None
        for field in valid.source:
            if field.startswith("existing-"):
                tracker_name = field[len("existing-"):]
                break

        if not tracker_name:
            search = valid.optional("search")
            trackers = todo.get_trackers(owner)
            trackers = filter(lambda r:
                    search.lower() in r["name"].lower()
                    or search.lower() in r["description"].lower(), trackers)
            trackers = sorted(trackers, key=lambda r: r["updated"], reverse=True)
            existing = [t.remote_id for t in (Tracker.query
                    .filter(Tracker.project_id == project.id)).all()]
            return render_template("tracker-new.html", view="new-resource",
                    owner=owner, project=project, trackers=trackers,
                    existing=existing, search=search)

        remote_tracker = todo.get_tracker(owner, tracker_name)

    tracker = Tracker()
    tracker.remote_id = remote_tracker["id"]
    tracker.project_id = project.id
    tracker.owner_id = owner.id
    tracker.name = remote_tracker["name"]
    tracker.description = remote_tracker["description"]
    if remote_tracker["defaultACL"]["browse"]:
        tracker.visibility = Visibility.PUBLIC
    else:
        tracker.visibility = Visibility.UNLISTED
    db.session.add(tracker)
    db.session.flush()

    event = Event()
    event.event_type = EventType.tracker_added
    event.tracker_id = tracker.id
    event.project_id = project.id
    event.user_id = project.owner_id
    db.session.add(event)

    todo.ensure_user_webhooks(owner)
    todo.ensure_tracker_webhooks(tracker)

    db.session.commit()

    return redirect(url_for("projects.summary_GET",
        owner=owner.canonical_name, project_name=project.name))

@trackers.route("/<owner>/<project_name>/trackers/manage")
@loginrequired
def manage_GET(owner, project_name):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    trackers = (Tracker.query
            .filter(Tracker.project_id == project.id)
            .order_by(Tracker.updated.desc()))

    terms = request.args.get("search")
    search_error = None
    try:
        trackers = search_by(trackers, terms,
                [Tracker.name, Tracker.description])
    except ValueError as ex:
        search_error = str(ex)

    trackers, pagination = paginate_query(trackers)
    return render_template("trackers-manage.html", view="tickets",
            owner=owner, project=project, trackers=trackers,
            search=terms, search_error=search_error,
            **pagination)

@trackers.route("/<owner>/<project_name>/trackers/delete/<int:tracker_id>")
@loginrequired
def delete_GET(owner, project_name, tracker_id):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    tracker = (Tracker.query
        .filter(Tracker.id == tracker_id)
        .filter(Tracker.project_id == project.id)).one_or_none()
    if not tracker:
        abort(404)
    return render_template("resource-delete.html", view="tickets",
            owner=owner, project=project, resource=tracker,
            resource_type="ticket tracker")

@trackers.route("/<owner>/<project_name>/trackers/delete/<int:tracker_id>",
        methods=["POST"])
@loginrequired
def delete_POST(owner, project_name, tracker_id):
    owner, project = get_project(owner, project_name, ProjectAccess.write)
    tracker = (Tracker.query
        .filter(Tracker.id == tracker_id)
        .filter(Tracker.project_id == project.id)).one_or_none()
    if not tracker:
        abort(404)
    tracker_name = tracker.remote_id
    db.session.delete(tracker)
    db.session.commit()

    valid = Validation(request)
    delete_remote = valid.optional("delete-remote") == "on"
    if delete_remote:
        todo.delete_tracker(owner, tracker_id)

    return redirect(url_for("projects.summary_GET",
        owner=owner.canonical_name, project_name=project.name))

hubsrht/templates/event.html
{% macro event(event, project=False) %}
<div class="event">
{% if event.event_type == EventType.source_repo_added %}
  <a
    href="{{event.source_repo.url()}}"
  >{{event.source_repo.owner.canonical_name}}/{{event.source_repo.name}}</a>
  <p>New {{event.source_repo.repo_type.value}} repository added</p>
{% elif event.event_type == EventType.mailing_list_added %}
  <a
    href="{{event.mailing_list.url()}}"
  >{{event.mailing_list.owner.canonical_name}}/{{event.mailing_list.name}}</a>
  <p>New mailing list added</p>
{% elif event.event_type == EventType.tracker_added %}
  <a
    href="{{event.tracker.url()}}"
  >{{event.tracker.owner.canonical_name}}/{{event.tracker.name}}</a>
  <p>New ticket tracker added</p>
{% elif event.event_type == EventType.external_event %}
  {{event.external_summary | md}}
  {{event.external_details | md}}
{% else %}
TODO: implement event type {{event.event_type}}
{% endif %}
  <small class="text-muted">
    {{event.created | date}}
    {% if project %}
    via <a href="{{url_for("projects.summary_GET",
      owner=event.project.owner.canonical_name,
      project_name=event.project.name)}}">{{event.project.name}}</a>
    {% endif %}
  </small>
</div>
{% endmacro %}

hubsrht/templates/featured-projects.html
{% extends "layout-full.html" %}
{% block title %}
<title>Featured projects on {{cfg("sr.ht", "site-name")}}</title>
{% endblock %}
{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
      <h3>Featured projects</h3>
      <div class="event-list">
        {% for feature in features %}
        {% set project = feature.project %}
        <div class="event">
          <h4>
            <a href="{{url_for("users.summary_GET",
              username=project.owner.username)}}"
            >{{project.owner.canonical_name}}</a>/<a
              href="{{url_for("projects.summary_GET",
                owner=project.owner.canonical_name,
                project_name=project.name)}}"
            >{{project.name}}</a>
          </h4>
          <blockquote style="margin-top: 0.5rem">
            {{feature.summary | md}}
          </blockquote>
          {% if project.tags %}
          <div class="tags">
          {% for tag in project.tags %}
            <a href="{{url_for("public.project_index", search="#"+tag)}}"
               class="tag" rel="nofollow">#{{tag}}</a>
          {% endfor %}
          </div>
          {% endif %}
        </div>
        {% endfor %}
        {{pagination()}}
      </div>
    </div>
  </div>
</div>
{% endblock %}

hubsrht/templates/mailing-list-new.html
{% extends "resource-new.html" %}
{% block title %}
<title>New mailing list - {{project.name}}</title>
{% endblock %}
{% block content %}
<div class="row">
  {# TODO: Hide this option for any projects which already have lists #}
  <form method="POST" class="col-lg-8">
    {{csrf_token()}}
    <h3>Use a common template</h3>
    <fieldset class="form-group">
      <div class="form-check">
        <label class="form-check-label">
          <input
            class="form-check-input"
            type="radio"
            name="template"
            value="public-inbox"
            checked> public-inbox
          <small id="visibility-unlisted-help" class="form-text text-muted">
            Direct users to send patches &amp; questions to a single "public
            inbox" shared with several other projects.
          </small>
        </label>
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <input
            class="form-check-input"
            type="radio"
            name="template"
            value="announce-devel">
          {{project.name}}-announce and
          {{project.name}}-devel
          <small id="visibility-unlisted-help" class="form-text text-muted">
            Separate mailing lists for low-frequency project announcements,
            and for patches &amp; development.
          </small>
        </label>
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <input
            class="form-check-input"
            type="radio"
            name="template"
            value="announce-devel-discuss">
          {{project.name}}-announce,
          {{project.name}}-devel, and
          {{project.name}}-discuss
          <small id="visibility-public-help" class="form-text text-muted">
            One list for announcements, one for patches &amp; development,
            and another for user support and discussion.
          </small>
        </label>
      </div>
    </fieldset>

    <div class="flex-grow-1 d-flex flex-row justify-content-end">
      <button
        type="submit"
        class="btn btn-primary align-self-end"
        name="from-template"
      >Create these mailing lists {{icon("caret-right")}}</button>
    </div>
  </form>
</div>
<form method="POST" class="row">
  {{csrf_token()}}
  <div class="col-lg-8">
    <h3 style="margin-top: 1rem">
      Or create a new mailing list
    </h3>
    <div class="form-group">
      <label for="{{ typename }}">Name</label>
      <input
        type="text"
        name="name"
        id="name"
        class="form-control {{ valid.cls("name") }}"
        value="{{ name or project.name }}" />
      {{ valid.summary("name") }}
      <div class="form-group">
        <label for="description">Description</label>
        <textarea
          type="text"
          name="description"
          id="description"
          class="form-control {{valid.cls("description")}}"
          rows="5"
          aria-describedby="description-help-text"
          placeholder="Introduce this mailing list to users and explain the posting rules. Markdown supported"
        >{{ description or "" }}</textarea>
        {{valid.summary("description")}}
      </div>
    </div>
    <div class="flex-grow-1 d-flex flex-row justify-content-end">
      <button
        type="submit"
        class="btn btn-primary align-self-end"
        name="create"
      >Create new mailing list {{icon("caret-right")}}</button>
    </div>
  </div>
</form>
{% if any(lists) or search %}
<div class="row">
  <div class="col-lg-8">
    <h3 style="margin-top: 1rem">
      Or add an existing mailing list
    </h3>
    {# TODO: Pagination #}
    <form class="form-group" method="POST">
      {{csrf_token()}}
      <input
        name="search"
        type="text"
        placeholder="Search mailing lists"
        class="form-control{% if search_error %} is-invalid{% endif %}"
        value="{{ search if search else "" }}" />
      {% if search_error %}
        <div class="invalid-feedback">{{ search_error }}</div>
      {% endif %}
    </form>
    <form method="POST" class="event-list select-resource">
      {{csrf_token()}}
      {% for list in lists %}
      <div class="event">
        <h3>
          {% if list["id"] in existing %}
          <button
            type="submit"
            class="pull-right btn btn-primary btn-lg"
            disabled
          >Already added&nbsp;{{ icon("caret-right") }}</button>
          {% else %}
          <button
            type="submit"
            name="existing-{{ list["name"] }}"
            class="pull-right btn btn-primary btn-lg"
          >Select list&nbsp;{{ icon("caret-right") }}</button>
          {% endif %}
          <a
            href="{{get_origin("lists.sr.ht",
              external=True)}}/{{ list["owner"]["canonicalName"] }}/{{list["name"]}}"
            target="_blank"
            rel="noopener"
          >{{ list["name"] }}</a>
        </h3>
      </div>
      {% endfor %}
    </form>
  </div>
</div>
{% endif %}
{% endblock %}

hubsrht/templates/mailing-lists-manage.html
{% extends "project-base.html" %}
{% block title %}
<title>Manage mailing lists - {{project.name}}</title>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12 event-list">
      <h3>Manage mailing lists</h3>
      <form>
        <input
          name="search"
          type="text"
          placeholder="Search mailing lists"
          class="form-control{% if search_error %} is-invalid{% endif %}"
          value="{{ search if search else "" }}" />
        {% if search_error %}
          <div class="invalid-feedback">{{ search_error }}</div>
        {% endif %}
      </form>
      {% for mailing_list in mailing_lists %}
      <div class="event">
        <h4>
          <a
            href="{{mailing_list.url()}}"
          >{{mailing_list.owner.canonical_name}}/{{mailing_list.name}}</a>
        </h4>
        {% if mailing_list.description %}
        {{ mailing_list.description | md }}
        {% endif %}
        <a
          class="btn btn-danger"
          href="{{url_for("mailing_lists.delete_POST",
            owner=project.owner.canonical_name,
            project_name=project.name,
            list_id=mailing_list.id)}}"
        >Remove mailing list {{icon('caret-right')}}</a>
      </div>
      {% endfor %}
      {{pagination()}}
    </div>
  </div>
</div>
{% endblock %}

hubsrht/templates/mailing-lists.html
{% extends "resource-list.html" %}
{% block title %}
<title>{{project.name}} mailing lists</title>
{% endblock %}
{% block resource_list %}
{% if not any(mailing_lists) %}
<div class="alert alert-info">
  This project has no public mailing lists.
</div>
{% endif %}
{% for mailing_list in mailing_lists %}
<div class="event">
  <h4>
    <a
      href="{{mailing_list.url()}}"
    >{{mailing_list.owner.canonical_name}}/{{mailing_list.name}}</a>
  </h4>
  {% if mailing_list.description %}
  {{ mailing_list.description | md }}
  {% endif %}
</div>
{% endfor %}
{% endblock %}

{% block sidebar %}
<a
  href="{{url_for("mailing_lists.new_GET",
          owner=owner.canonical_name, project_name=project.name)}}"
  class="btn btn-primary btn-block"
>Add mailing list&nbsp;{{icon('caret-right')}}</a>
<a
  href="{{url_for("mailing_lists.manage_GET",
          owner=owner.canonical_name, project_name=project.name)}}"
  class="btn btn-default btn-block"
>Manage lists&nbsp;{{icon('caret-right')}}</a>
{% endblock %}

hubsrht/templates/project-base.html
{% extends "layout.html" %}
{% block body %}
<div class="header-tabbed">
  <div class="container">
    {% include 'project-nav.html' %}
  </div>
</div>
{% if project.description %}
<div class="header-extension">
  <div class="container">{{ project.description }}</div>
</div>
{% endif %}
{% block content %}
{% endblock %}
{% endblock %}

hubsrht/templates/project-feed-rss.html
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
{% import "event-rss.html" as event_rss_tpl with context %}
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{project.name}} activity</title>
    <link>{{url_for("projects.summary_GET",
      owner=project.owner.canonical_name,
      project_name=project.name)}}</link>
    <description>{{project.owner.canonical_name}}/{{project.name}}</description>
    <atom:link href="{{url_for('projects.feed_rss_GET',
      owner=project.owner.canonical_name,
      project_name=project.name)}}" rel="self" type="application/rss+xml" />
    {% for event in events %}
    {{ event_rss_tpl.event(event, project) }}
    {% endfor %}
  </channel>
</rss>

hubsrht/templates/resource-list.html
{% extends "project-base.html" %}
{% block title %}
<title>{{project.name}} {{view}} - {{cfg("sr.ht", "site-name")}}</title>
{% endblock %}
{% block content %}
<form class="container">
  <div class="row">
    <div class="form-group col-md-12">
      <input
        name="search"
        type="text"
        placeholder="Search {{view}}"
        class="form-control{% if search_error %} is-invalid{% endif %}"
        value="{{ search if search else "" }}" />
      {% if search_error %}
        <div class="invalid-feedback">{{ search_error }}</div>
      {% endif %}
    </div>
  </div>
  <div class="row">
    {% if current_user and current_user.id == owner.id %}
    <div class="col-md-9 event-list">
    {% else %}
    <div class="col-md-12 event-list">
    {% endif %}
      {% block resource_list %}
        TODO: populate resource list
      {% endblock %}
      {{pagination()}}
    </div>
    {% if current_user and current_user.id == owner.id %}
    <div class="col-md-3">
      {% block sidebar %}
      TODO: populate sidebar
      {% endblock %}
    </div>
    {% endif %}
  </div>
</form>
{% endblock %}

hubsrht/templates/resource-new.html
{% extends "layout.html" %}
{% block body %}
<div class="header-tabbed">
  <div class="container">
    <h2>
      <a
        href="{{url_for("users.summary_GET", username=owner.username)}}"
      >{{owner.canonical_name}}</a>/<wbr>{{project.name}}
    </h2>
    {% macro link(path, title, alternates, cls="") %}
    <a
      class="nav-link {% if view == title or view in alternates %}active{% endif %} {{cls}}"
      href="{{ path }}">{{ title }}</a>
    {% endmacro %}
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link"
          href="{{url_for("projects.summary_GET",
            owner=owner.canonical_name, project_name=project.name)}}"
        >{{icon('caret-left')}}&nbsp;cancel</a>
      </li>
    </ul>
  </div>
</div>
<div class="container">
  {% block content %}
  {% endblock %}
</div>
{% endblock %}

hubsrht/templates/trackers.html
{% extends "resource-list.html" %}
{% block resource_list %}
{% if not any(trackers) %}
<div class="alert alert-info">
  This project has no public ticket trackers.
</div>
{% endif %}
{% for tracker in trackers %}
<div class="event">
  <h4>
    <a href="{{tracker.url()}}">~{{tracker.owner.username}}/{{tracker.name}}</a>
  </h4>
  {% if tracker.description %}
  {{ tracker.description | md }}
  {% endif %}
</div>
{% endfor %}
{% endblock %}

{% block sidebar %}
<a
  href="{{url_for("trackers.new_GET", owner=owner.canonical_name,
    project_name=project.name)}}"
  class="btn btn-primary btn-block"
>Add tracker&nbsp;{{icon('caret-right')}}</a>
<a
  href="{{url_for("trackers.manage_GET",
          owner=owner.canonical_name, project_name=project.name)}}"
  class="btn btn-default btn-block"
>Manage trackers&nbsp;{{icon('caret-right')}}</a>
{% endblock %}